// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCRUD.Data.DataContext;

#nullable disable

namespace SimpleCRUD.Data.Migrations
{
    [DbContext(typeof(SimpleCrudDbContext))]
    [Migration("20260312211835_FixingEntities")]
    partial class FixingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimpleCRUD.Data.Entities.Application", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationID");

                    b.Property<string>("ApplicationDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId")
                        .HasName("PK_ApplicationID");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationRoleID");

                    b.Property<string>("ApplicationRoleName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("ApplicationRoleId")
                        .HasName("PK_ApplicationRoleID");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationUserID");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationID");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("ApplicationUserId")
                        .HasName("PK_ApplicationUserID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("UserId");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationUserRole", b =>
                {
                    b.Property<Guid>("ApplicationUserRolesId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationUserRolesID");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationID");

                    b.Property<Guid>("ApplicationRoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationRoleID");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ApplicationUserID");

                    b.HasKey("ApplicationUserRolesId")
                        .HasName("PK_ApplicationUserRolesID");

                    b.HasIndex("ApplicationId");

                    b.HasIndex("ApplicationRoleId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("ApplicationUserRoles");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__3214EC27BB834F9E");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleID");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("RoleName")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A8C985CAD");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationUser", b =>
                {
                    b.HasOne("SimpleCRUD.Data.Entities.Application", "Application")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleCRUD.Data.Entities.User", "User")
                        .WithMany("ApplicationUsers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserID");

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationUserRole", b =>
                {
                    b.HasOne("SimpleCRUD.Data.Entities.Application", "Application")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("ApplicationId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationID");

                    b.HasOne("SimpleCRUD.Data.Entities.ApplicationRole", "ApplicationRole")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("ApplicationRoleId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationRoleID");

                    b.HasOne("SimpleCRUD.Data.Entities.ApplicationUser", "ApplicationUser")
                        .WithMany("ApplicationUserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .IsRequired()
                        .HasConstraintName("FK_ApplicationUserID");

                    b.Navigation("Application");

                    b.Navigation("ApplicationRole");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.Application", b =>
                {
                    b.Navigation("ApplicationUserRoles");

                    b.Navigation("ApplicationUsers");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationRole", b =>
                {
                    b.Navigation("ApplicationUserRoles");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ApplicationUserRoles");
                });

            modelBuilder.Entity("SimpleCRUD.Data.Entities.User", b =>
                {
                    b.Navigation("ApplicationUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
